/* This file was generated by syncqt with the info from sync.profile. */
#ifndef QT_ACTIVEQT_VERSION_H
#define QT_ACTIVEQT_VERSION_H

#define ACTIVEQT_VERSION_STR "5.0.0"

#define ACTIVEQT_VERSION 0x050000

#endif // QT_ACTIVEQT_VERSION_H
